<a href="https://colab.research.google.com/github/PAvdokhin/python_prakt2/blob/sem_8/%D0%A1%D0%B5%D0%BC%D0%B8%D0%BD%D0%B0%D1%80%208%20%22%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_numpy_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Семинар NumPy

При выполнении заданий не используйте циклы и условные операторы. 
Внизу есть подсказки, какие функции можно/нужно использовать в некоторых из заданий, чтобы не тратить время на их поиск:)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

1. Создайте вектор, состоящий из нулей, длиной 10.

In [ ]:
import numpy as np
a = np.zeros((10))

print(a)
print(a.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10


2. Создайте вектор, состоящий из нулей, длиной 10, где 4-ым элементом будет 1.

In [ ]:
import numpy as np
a = np.zeros((10))
a[3] = 1

print(a)
print(a.size)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
10


3. Создайте вектор длиной 10, заполненный числом 14,8.

In [ ]:
import numpy as np
b = np.full((10), [14.8])
print((b))

[14.8 14.8 14.8 14.8 14.8 14.8 14.8 14.8 14.8 14.8]


4. Создайте вектор со значениями от 23 до 38.

In [ ]:
import numpy as np
a = np.arange(23, 39)
print(a)

[23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]


5. Переверните вектор (последнее значение становится первым и т.д.).

In [ ]:
import numpy as np
a = np.arange(5)
print(a)
print(a[::-1])

[0 1 2 3 4]
[4 3 2 1 0]


6. Из вектора длиной 9 создайте матрицу 3x3.

In [ ]:
import numpy as np
a = np.arange(1, 10)
b = a.reshape(3, 3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


7. Создайте матрицу размерностью 3x3 и значениями от 0 до 8.

In [ ]:
import numpy as np
a = np.arange(9).reshape(3, 3)
print(a)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


8. Найдите индексы ненулевых элементов в массиве `a`.


In [ ]:
a = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(a))


(array([0, 1, 4]),)


9. Создайте массив 10x10 со случайными значениями и найдите наименьшее и наибольшее значения в нём.

In [ ]:
a = np.random.random((10, 10))
print(a.min(), a.max())

0.03964774263967008 0.9925871838649266


10. Создайте вектор длиной 15 со случайными значениями и найдите индексы, содержащие наименьшее и наибольшее значения.

In [ ]:
a = np.random.random((15))
print(np.argmax(a), np.argmin(a))

14 4


11. Создайте вектор со случайными значениями размерностью 30 и вычислите среднее значение.

In [ ]:
a = np.random.random((30))
print(np.mean(a))

0.5723827302644773


12. Создайте вектор со случайными значениями размерностью 3х10 и вычислите отдельно среднее значение в каждой строке (размерность итогового массива 3х1) и в каждом столбце (размерность итогового массива 10x1).

In [ ]:
a = np.random.random((3, 10))
print(np.mean(a, axis = 1))
print(np.mean(a, axis = 0))

[0.44549652 0.4711617  0.57137079]
[0.60644819 0.58132147 0.41796016 0.6748645  0.23800657 0.4015179
 0.66872184 0.25364943 0.56047398 0.55713268]


13. Добавьте границы (состоящие из нулей) вокруг существующего массива. В итоге должен получиться массив такого вида:

``` 
00000
01110
01110
00000
 ```

In [ ]:
a = np.ones((2, 3))
b = np.pad(a, pad_width = 1, constant_values=0)
print(b)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


14. Умножьте матрицу 5x3 на матрицу 3х2.

In [ ]:
a = np.random.randint(1, 16, size = (5, 3))
b = np.random.randint(1,16, size = (3, 2))
c = np.matmul(a, b)
print(a)
print(b)
print(c)

[[ 3  7  1]
 [ 9 13  1]
 [ 1  9  3]
 [15  3  6]
 [11  6  2]]
[[ 9 11]
 [ 6  7]
 [ 5  7]]
[[ 74  89]
 [164 197]
 [ 78  95]
 [183 228]
 [145 177]]


15. Найдите общие значения двух массивов (элементы в их пересечении).

In [ ]:
a = np.random.randint(1, 21, size = (6))
b = np.random.randint(1, 21, size = (6))
print(a)
print(b)
print(np.intersect1d(a, b))


[ 1  2  5  1  4 18]
[20 18 14 16 20 17]
[18]


16. Создайте вектор со случайными значениями длиной 10 и отсортируйте его.

In [ ]:
from numpy.core.fromnumeric import sort
a = np.random.randint(1,101, size = (10))
sort(a)
print(a)

[30 83 52 80  7 38 26 45 83 10]


17. Создайте вектор со случайными значениями размерностью 10 и замените наибольшее значение нулём.

In [ ]:
a = np.random.randint(1, 101, size = (10))
a[np.where(a == a.max())] = 0
print(a)



[18 27 17 15  0 51  2 85 66 81]


18. Создайте матрицу 3х3 и “растяните” её в вектор (так, чтобы размерность стала 1х9) по крайней мере двумя способами.


In [ ]:
a = np.random.randint(1, 21, size = (3, 3))
b = np.random.randint(1, 21, size = (3, 3))
print(a)
print(a.ravel())
print(b)
print(b.flatten())


[[ 4  5 16]
 [17  8 12]
 [ 8 15 16]]
[ 4  5 16 17  8 12  8 15 16]
[[ 1  8  6]
 [ 8  6  6]
 [13  4 18]]
[ 1  8  6  8  6  6 13  4 18]


19. Создайте матрицу 4х4 и из каждой строки вычтите максимальное значение этой строки. Обратите внимание, что в полученной матрице в каждой строке одним из элементов должен быть 0.

Пример: из матрицы

```
[[0.60682249 0.7449185  0.03185808 0.15218245]
 [0.55140296 0.36923363 0.52486168 0.72297047]
 [0.63520354 0.54560057 0.9501767  0.05801644]
 [0.14608529 0.56327529 0.90571396 0.66212734]]
```
должна получиться матрица

```
[[-0.138096    0.         -0.71306042 -0.59273604]
 [-0.17156751 -0.35373684 -0.19810879  0.        ]
 [-0.31497315 -0.40457613  0.         -0.89216025]
 [-0.75962867 -0.34243867  0.         -0.24358662]]
```

***Подсказка***: при нахождении максимального элемента укажите аргумент `keepdims=True`.


In [ ]:
a = np.random.randint(1, 21, size = (4, 4))
a.max(axis=1, keepdims = True)
b = a - a.max(axis=1, keepdims=True)

print(a)
print(a.max(axis=1, keepdims = True))
print(b)


[[17  5  3  4]
 [ 2 15  4 20]
 [16  1  5  4]
 [20 14  3 12]]
[[17]
 [20]
 [16]
 [20]]
[[  0 -12 -14 -13]
 [-18  -5 -16   0]
 [  0 -15 -11 -12]
 [  0  -6 -17  -8]]


20. Считайте массив из текстового файла (предварительно его создав, элементы массива - числа с плавающей точкой (float)) и совершите над ним какую-либо операцию.

Пример текста в файле:
`1.2 5.6 7.8`

In [ ]:
with open("np20.txt", "r") as f:
  print(f.read())

9, 8, 2, 10, 5




---

# Подсказки

1. zeros
3. full
4. arange
6. reshape
8. nonzero
9. Для создания массива со случайными значениями: np.random.random(shape), shape - размерность массива. Не забудьте, что если shape > 1, то размерности передаются в виде кортежа!
10. argmax, argmin
11. mean
13. pad
14. dot
15. Инициализировать массивы можно функцией np.random.randint() - в качестве аргументов передайте свои значения. Пересечение - intersect1d
16. sort
18. Один способ - flatten, другой уже использовался в предыдущих заданиях.
20. fromfile

# Новый раздел